name: 04-01-runners
on: workflow_dispatch # event tirgger
jobs: 
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
  my-second-job:
    runs-on: windows-latest
    steps:
      - run: echo "Hello World"
  my-third-job:
    runs-on: macos-latest
    steps:
        - run: echo "Hello World"
