name: 07-04-context 

on: workflow_dispatch
env:
    lacalenvvar: ${{ vars.test.TEST_ENV_REPO }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Display Event Information
       run: echo "hello world ${{ env.lacalenvvar }}"