name: 07-04-context 

on: workflow_dispatch
env:
    localenvvar: ${{ vars.TEST_ENV_REPO }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
     - name: Display Event Information
       run: echo "hello world ${{ env.localenvvar }}"