name: 10-01-functions
#on: push
on: workflow_dispatch
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: |
          echo "Hello World"
          exit 1
      - name: step 2
        run: echo "hello"
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step 1
        run: echo "Hello World"